name: Deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Deploy
        uses: xueqili02/xueqili.github.io@main
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REPOSITORY: xueqili02/xueqili.github.io
          # BRANCH: gh-pages
          # CNAME: keep-start.xpoet.cn